spring:
  config:
    activate:
      on-profile:

  # 데이터 소스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/TEST?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: blind42blind42

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
    logging:
      level:
        org.hibernate.SQL: debug
